### ISSUE TITLE
Deprecated Issues

### ISSUE THREAD

**Issue by swissdude** [alibuyukkilinc/PHPExcel-php8#1]
In case someone stumbles upon this, there's still some deprecated stuff in there.

Specifically in the file Calculation/Functions.php

Look out for stuff like this:

`$value{0}`

this is deprecated and should now be written as `$value[0]`.

There are a few of these notations in that file. If you correct them all, this version of PHPExcel should work with PHP8

**Comment by alibuyukkilinc** [comment]
Thank yo ı updated to repostory.
